### ISSUE TITLE
Leap 15 Image - kein Login möglich

### ISSUE THREAD

**Issue by netzvieh** [betacloud/images#11]
openSUSE Leap 15 (und vermutlich auch 42.3) haben das Problem, dass man sich nicht mehr als root User anmelden kann, aber auch kein anderer User existiert.

Auf der 20180628 ging das noch.

**Comment by berendt** [comment]
Ist ein Fehler in den openSUSE Images die von der Community kommen. Workaround dafür ist dokumentiert. Siehe dazu https://docs.betacloud.io/end-user/generic/cloud-init.html#add-users.

Ansonsten das 20180628 Image nehmen, das ist noch vorhanden und nutzbar. Nur nicht im Horizon sichtbar.

**Comment by berendt** [comment]
Geht mit 20190214 nun wieder.
